# This program converts the index.json file generated by the exiftool to a geojson file
# that can be used in a map. The geojson file contains the location of the photos and
# the path of the photos. The path is used to display the photos in the map.
# The geojson file is saved in the same repository as the index.json file.
# The geojson file is named as index.geojson
# The geojson file can be used in a map.

import json
import os
import sys
import argparse
from datetime import datetime
import re

def ddm2dec(dms_str):
    """Return decimal representation of DDM (degree decimal minutes)

    >>> ddm2dec("45° 17,896' N")
    48.8866111111F
    """

    dms_str = re.sub(r'\s', '', dms_str)

    sign = -1 if re.search('[swSW]', dms_str) else 1

    numbers = [*filter(len, re.split('\D+', dms_str, maxsplit=4))]

    degree = numbers[0]
    minute_decimal = numbers[1]
    decimal_val = numbers[2] if len(numbers) > 2 else '0'
    minute_decimal += "." + decimal_val

    return sign * (int(degree) + float(minute_decimal) / 60)


def convert_latlong(photo):
    """Convert the latitude and longitude of a photo to decimal degrees

    exiftool exports in this format:

      "GPSPosition": "45 deg 33' 3.55\" N, 73 deg 36' 53.61\" W",

    and we want this format:

      "latitude": 45.55098611111111,
      "longitude": -73.61489166666666,
    """
    # Get the latitude and longitude of the photo
    latlong = photo["GPSPosition"].split(", ")

    # Convert the latitude and longitude to decimal degrees
    photo["latitude"] = ddm2dec(latlong[0])
    photo["longitude"] = ddm2dec(latlong[1])


def convert(exif_index, base_url):
    # This function converts the index.json file to a geojson file
    # Input: index.json file
    # Output: geojson file

    # Create a geojson file
    geojson = {"type": "FeatureCollection", "features": []}

    # Create a feature for each photo
    for photo in exif_index:
        if "GPSPosition" not in photo:
            print('No GPSPosition for ' + photo["SourceFile"])
            continue
        # Create a feature
        feature = {
            "type": "Feature",
            "properties": {},
            "geometry": {"type": "Point", "coordinates": []},
        }

        convert_latlong(photo)
        # Add the location of the photo to the feature
        feature["geometry"]["coordinates"] = [photo["longitude"], photo["latitude"]]

        # Add the path of the photo to the feature
        feature["properties"]["path"] = base_url + photo["SourceFile"]

        # Add the feature to the geojson
        geojson["features"].append(feature)
    return geojson


if __name__ == "__main__":
    # Create a parser
    parser = argparse.ArgumentParser(description="Convert index.json to geojson")

    # Add arguments
    parser.add_argument("index", help="index.json file")
    parser.add_argument(
        "base_url",
        help="where the photos are hosted",
        nargs="?",
        default="https://raw.githubusercontent.com/rngadam/lane-data/main/sources/")

    # Parse the arguments
    args = parser.parse_args()

    # Open the index.json file
    with open(args.index) as json_file:
        exif_index = json.load(json_file)

    # Convert the index.json file to a geojson file
    geojson = convert(exif_index, args.base_url)

    # Save the geojson file
    with open("index.geojson", "w") as outfile:
        json.dump(geojson, outfile, indent=4)
